version: '3.9'

services:

    nginx:
        build:
            context: ./nginx
        restart: unless-stopped
        container_name: ${CONTAINER_NAME:-unnamed}-nginx
        working_dir: /var/www/app
        environment:
            - VIRTUAL_HOST=${DOMAIN}
            - LETSENCRYPT_HOST=${DOMAIN}
        depends_on:
            - php
        volumes:
            - ${PROJECT_PATH:-../}:/var/www/app
            - ./nginx/conf.d/:/etc/nginx/conf.d
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/sites-enabled/app.conf:/etc/nginx/sites-enabled/${CONTAINER_NAME:-unnamed}.conf
            - ./nginx/logs/access.log:/var/log/nginx/access.log
            - ./nginx/logs/error.log:/var/log/nginx/error.log
            - /etc/localtime:/etc/localtime:ro
        networks:
            - frontend
            - backend

    php:
        build:
            context: ./php
            args:
                PHP: ${PHP_VERSION}
                NAME: ${CONTAINER_NAME:-unnamed}
        user: 1000:1000
        restart: unless-stopped
        container_name: ${CONTAINER_NAME:-unnamed}-php
        working_dir: /var/www/app
        stdin_open: true
        tty: true
        entrypoint:
            - /bin/bash
            - /init.sh
            - ${APP_ENV:-dev}
        environment:
            - PHP_OPCACHE_VALIDATE_TIMESTAMPS=1
            - VIRTUAL_PROTO=fastcgi
            - TERM=xterm-256color
            - PS1=${PS1}
        volumes:
            - ./bash/.bash_aliases:/home/${USER}/.bash_aliases
            - ./bash/.bashrc:/home/${USER}/.bashrc
            - ./bash/init.sh:/init.sh

            - ${COMPOSER_CONFIG_PATH:-./composer/.config}:/.composer
            - ${COMPOSER_CACHE_PATH:-./composer/.cache}:/.cache/composer
            - ${YARN_PATH:-./yarn}:/home/${USER}/.yarn

            - ${YARNRC_PATH:-./yarn/.yarnrc}:/home/${USER}/.yarnrc
            - ${YARN_CACHE_PATH:-./yarn/.config}:/home/${USER}/.cache

            - ${PROJECT_PATH:-../}:/var/www/app

            - /home/${USER}/.ssh:/home/${USER}/.ssh:rw
            - /etc/group:/etc/group:ro
            - /etc/passwd:/etc/passwd:ro
            - /etc/shadow:/etc/shadow:ro

            - /etc/localtime:/etc/localtime:ro
            - ./php/php.ini:/usr/local/etc/php/conf.d/custom.php.ini
        networks:
            - sql
            - backend

networks:
    backend:
        driver: bridge
        name: ${CONTAINER_NAME:-unnamed}_backend_network

    frontend:
        name: ${PROXY_NETWORK_NAME:-docker_engine_proxy}
        external: true

    sql:
        name: ${SQL_NETWORK_NAME:-docker_engine_sql}
        external: true
